name: left_custom
timestamp: 1494950266
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-3589: 'Logo / Image'
    logo-7431: 'Logo / Image'
  menu:
    menu-9952: Menu
  social:
    social-4917: Social
  widget:
    position-widget-1011: Widget
  custom:
    custom-2543: 'Left Sidebar'
    custom-6150: 'Flexible Layouts'
  contentarray:
    contentarray-8482: 'WordPress Posts'
  copyright:
    copyright-7553: Copyright
  horizontalmenu:
    horizontalmenu-4400: 'Horizontal Menu'
  totop:
    totop-9371: 'To Top'
  mobile-menu:
    mobile-menu-9585: Mobile-menu
inherit:
  default:
    navigation: navigation
    logo-3589: logo-9608
    menu-9952: menu-6409
    social-4917: social-3171
    footer: footer
    logo-7431: logo-9571
    copyright-7553: copyright-1736
    horizontalmenu-4400: horizontalmenu-9034
    totop-9371: totop-8670
    offcanvas: offcanvas
    mobile-menu-9585: mobile-menu-5697
  left_sidebar:
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    sidebar: sidebar
    custom-2543: custom-6361
    custom-6150: custom-9374
