version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
layout:
  navigation: {  }
  /header/:
    -
      - position-widget-1011
  intro: {  }
  features: {  }
  utility: {  }
  above: {  }
  testimonials: {  }
  expanded: {  }
  /container-main/:
    -
      -
        'sidebar 25':
          -
            - custom-6361
          -
            - contentarray-6590
      -
        'mainbar 75':
          -
            - contentarray-8482
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: ''
  intro:
    type: section
    inherit:
      outline: left_sidebar
      include:
        - attributes
        - block
        - children
  features:
    type: section
    inherit:
      outline: left_sidebar
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: left_sidebar
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: left_sidebar
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: left_sidebar
      include:
        - attributes
        - block
        - children
  expanded:
    type: section
    inherit:
      outline: left_sidebar
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    attributes:
      class: ''
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - children
        - attributes
content:
  position-widget-1011:
    attributes:
      widget: '{"type":"widget","widget":"metaslider_widget","title":"Meta Slider","options":{"widget":{"slider_id":"152","title":""}}}'
      key: widget
  custom-6361:
    title: 'Left Sidebar'
    attributes:
      html: "<h3>Left Sidebar</h3>\n<p class=\"nomarginbottom\"> A left column layout example. The sidebar is independent from the Mainbody so can have multiple rows and columns, separate from the Mainbody area.</p>"
    block:
      variations: box1
  contentarray-6590:
    title: 'WordPress Posts'
    attributes:
      post:
        filter:
          categories: ''
          sticky: ''
        limit:
          total: '10'
          columns: '1'
          start: '0'
        sort:
          orderby: date
          ordering: DESC
        display:
          image:
            enabled: ''
          title:
            enabled: show
            limit: '20'
          date:
            enabled: ''
          read_more:
            enabled: ''
          author:
            enabled: ''
          category:
            enabled: ''
          comments:
            enabled: ''
          text:
            type: ''
    block:
      class: sidebar-title
      variations: box2
  contentarray-8482:
    title: 'WordPress Posts'
    attributes:
      post:
        filter:
          categories: '1'
          sticky: ''
        limit:
          total: '6'
          columns: '3'
          start: '0'
        sort:
          orderby: date
          ordering: DESC
        display:
          image:
            enabled: show
          title:
            enabled: show
            limit: '20'
          read_more:
            enabled: show
            css: cus_button
          category:
            enabled: ''
          comments:
            enabled: ''
          text:
            type: content
            limit: '100'
